### ISSUE TITLE
support null?

### ISSUE THREAD

**Issue by dominictarr** [kemitchell/lamos.js#2]
the way json encodes null is very useful because sometimes you need to register something as deleted.

```
        : Object.keys(data)
                 ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at recurse (/home/dominic/c/scuttlebot/node_modules/lamos/stringify.js:43:18)
    at /home/dominic/c/scuttlebot/node_modules/lamos/stringify.js:52:13
    at Array.map (native)
    at recurse (/home/dominic/c/scuttlebot/node_modules/lamos/stringify.js:45:8)
    at /home/dominic/c/scuttlebot/node_modules/lamos/stringify.js:52:13
    at Array.map (native)
    at recurse (/home/dominic/c/scuttlebot/node_modules/lamos/stringify.js:45:8)
    at Object.exports.unsorted [as stringify] (/home/dominic/c/scuttlebot/node_modules/lamos/stringify.js:2:10)
    at rpc.config (/home/dominic/c/scuttlebot/bin.js:112:25)
```

**Comment by kemitchell** [comment]
These are very early days, and I could not be more open to feedback.  But at the moment, I lean against adding null and its cousin, empty string.  Here's why.

From a practical point of view, it's always possible to get the semantics of null with more context.  In other words, express the absence of value in schema.  If map values may be null, you can omit the properties altogether.  If list members may be null, you can "wrap" all elements of the list in ways that make clear which are nulls. For example:

```json
[
  "x",
  null,
  "y"
]
```

Becomes:

```lamos
- value: x
- null: yes
- value: y
```

Or you can make "null" a magic value in the context:

```lamos
- value: x
- null
- value: y
```

At a more conceptual level, null is in essence its own atomic type. LAMOS supports just one atomic type at the moment: strings.  Adding another wouldn't be hard to implement, but the implementation would become necessarily more complex than what I'm hoping LAMOS will be.

Again, could not be more open to hearing otherwise. Experiment!

**Comment by dominictarr** [comment]
but you'll just push that "extra" complexity out to the application!
potential users could have different ways to encode the empty string and null, it ends up being part of the spec, or being a total mess, anyway.

**Comment by kemitchell** [comment]
You're absolutely right. If there's unavoidable complexity in a solution combining application and serialization, simplifying the serialization complicates the application.

JSON doesn't support dates natively, for example.  You have to "encode" them in schema, most commonly as strings (ISO 8601), but perhaps as numbers (Unix time), or even `{"year":2017, "month":6, day: 6}`.  YAML generalizes and specifies default behavior, so `- 2017-06-06` ends up a `Date` list item in Ruby. But that means YAML also has to provide type annotations, like `- !!str 2017-06-06`, so data can avoid triggering the defaults.

The same logic for `null` here applies to any other data type that isn't natively supported, in any serialization. So the question is where you draw the line. Which data types are so useful, and so common, with near consensus about encoding, that the serialization should support them?

Good cost-benefit for `null`/`nil`/null-pointer isn't universally acknowledged. In particular, many functional languages do without them, often substituting `Maybe` or `Option` types affording the necessary context in the type system.

Part of me suspects that an intentionally simplistic serialization, like LAMOS, couldn't be a good fit for work in languages like JavaScript, where `null`s are so deeply ingrained. But on the other hand, because `null` is so ingrained, JavaScript programmers are more accustomed than most to handling that kind of complexity --- every time they expose an API!

**Comment by dominictarr** [comment]
> So the question is where you draw the line. Which data types are so useful, and so common, with near consensus about encoding, that the serialization should support them?

Absolutely. I'm just saying you should draw that line following the precedent set by JSON. That means null, true, false, but not dates or undefined. No, it's not the best possible serialization format, but it is the most popular! Instead of explaining all the reasons why you chose these specific tradeoffs, you just say "supports the same types as JSON" and everyone will know what you mean.

`!!str 2017-06-06`

Oh my, what would have been wrong with `"2017-06-06"`?.. Adding this to my book in the chapter "YAML: a great idea, ruined"

**Comment by kemitchell** [comment]
I'm actually not sure if the quotes in `"2016-06-06"` will prevent Date interpretation. Good thought.

Quoting is probably what it would take to support "magic strings", starting from something like LAMOS. Once you have that facility, you easily add other magic values with meanings in a different type. That would come at the cost of a more complex syntax.

But even `null`, `true`, and `false` wouldn't give LAMOS full JSON parity. It would still lack IEEE 754 numbers.

**Comment by dominictarr** [comment]
yes, numbers too. Anyway, all of these things can be parsed by regular expressions, because they have no arbitrary nested state, just inside quotes or not. Where as for example, [] or {} can't be.
